name: Deploy to GitHub Pages (Fixed)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Clear npm cache
      run: npm cache clean --force
      
    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps --prefer-offline --no-audit
      
    - name: Create .env.production
      run: |
        cat > .env.production << EOF
        # Firebase Configuration
        REACT_APP_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
        REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
        REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
        REACT_APP_FIREBASE_VAPID_KEY=${{ secrets.FIREBASE_VAPID_KEY }}
        
        # App Configuration
        REACT_APP_NAME=To-Round
        REACT_APP_VERSION=0.0.2
        REACT_APP_ENVIRONMENT=production
        EOF
        
    - name: Generate Service Worker
      run: |
        npm run generate-sw --legacy-peer-deps
      
    - name: Build
      run: |
        npm run build --legacy-peer-deps
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v4
